### ISSUE TITLE
When using interleaved tables, specifying foreign keys results in both FKs and interleaving

### ISSUE THREAD

**Issue by geudrik** [googleapis/python-spanner-sqlalchemy#100]
## Expected Behavior
Ideally, I think that if we specify interleaving on a table, FK relationships should be ignored (when creating DDL statements for creates). The docs for Spanner indicate to use one or the other, but spanners API allows both to be done simulcisely. 

Thoughts?

## Actual Behavior
N/A

## Steps to Reproduce the Problem

Define a table with Interleaving, and a FK (on the parent key)

**Comment by IlyaFaer** [comment]
> The docs for Spanner indicate to use one or the other

@geudrik, could you attach a link to the doc you're relating?

There is a code snippet in [foreign keys and interleaved tables comparison section](https://cloud.google.com/spanner/docs/foreign-keys/overview#fk-and-table-interleaving), which shows how both foreign key and interleaved table relations can be used in the same time. Thus, the features are not considered as mutually exclusive.

**Comment by geudrik** [comment]
Yeah, this description wasn't all that clear, my mistake. This is in reference to having a FK defined on an interleaved table, _where the FK is the parent row's ID_. This is totally allowable in the DDL, but is redundant given the nature of interleaving, and possibly has some overhead cost (pure speculation on that last bit)?

The doc I was referring to is actually the one you linked [here](https://cloud.google.com/spanner/docs/foreign-keys/overview#fk-and-table-interleaving) - this indicates to me that you shouldn't use a FK relationship for a column you're interleaving on (though it's not explicitly stated).

**Comment by geudrik** [comment]
Example here - `rel_malware_communicates_with` is interleaved on `ob_malware`, and has `rel_malware_communicates_with.malware_id` as a foreign key to `ob_malware.malware_id` (redundant and not necessary).
```sql
CREATE TABLE ob_malware (
	malware_id STRING(MAX) NOT NULL,
	malware_name STRING(MAX),
) PRIMARY KEY (malware_id);


CREATE TABLE rel_malware_communicates_with (
	malware_id STRING(MAX) NOT NULL,
	relation_id STRING(MAX) NOT NULL,
	FOREIGN KEY (malware_id) REFERENCES ob_malware(malware_id),
) PRIMARY KEY (malware_id, relation_id),
INTERLEAVE IN PARENT ob_malware;
```

**Comment by IlyaFaer** [comment]
@geudrik, I see, thanks.

I also found [the section](https://cloud.google.com/spanner/docs/schema-and-data-model#parent-child_table_relationships) where it's recommended to use one of, but not both mechanisms. So, it can be considered as a bad practise.

@skuruppu, I suppose if we want to restrict cases when foreign key duplicates an interleaved relation, we should do this on backend, to make it actual for all the languages at once. Still, it's already marked as a not recommended practise, which is probably enough.

**Comment by geudrik** [comment]
@IlyaFaer GCP Case 28511772 was worked a few weeks back, which also describes this behavior

**Comment by larkee** [comment]
Cloud Spanner allows for both to be used simultaneously which is why the API supports this. However, as per [the updated documentation](https://cloud.google.com/spanner/docs/foreign-keys/overview#fk-and-table-interleaving):

> Google recommends that you choose to represent parent-child relationships either as interleaved tables or as foreign keys, but not both. Using both is redundant and may consume additional storage and computing resources in order to verify constraints and maintain backing indexes.

I would prefer to not make a choice between the two for the user (e.g. ignore FKs over interleaving) as different use cases have different requirements.

**Comment by geudrik** [comment]
OK, cool. So given that, would it be worth while to have an option maybe that would strip FK's out of the DDL generated if the column is interleaved?

**Comment by larkee** [comment]
@geudrik I'm a little confused by your request. My understanding is that SQLAlchemy will generate the DDL based on the user code so the user would have to be specifying both FKs _and_ interleaving for this case to occur. Wouldn't it make more sense to just include logic in the user code to not specify FKs when using interleaving?

Please let me know what your use case is if this is not an option :+1:

**Comment by geudrik** [comment]
It's definitely an option, and I think you're right in thinking about it more. My initial thought was to make interleaved columns explicitly clear what they are/were via the visual cue in the column def that it's, in effect, an FK. It's complicated, ofc.
