### ISSUE TITLE
SQLAlchemy 1.4

### ISSUE THREAD

**Issue by hadim** [googleapis/python-spanner-sqlalchemy#105]
Are you planning to support SQLAlchemy 1.4? It's likely the last 1.* version before a 2.0. See https://docs.sqlalchemy.org/en/14/changelog/migration_20.html

**Comment by IlyaFaer** [comment]
Didn't have time to take a closer look and remember what's happening there, sorry.

So, when we're trying to execute tests with SQLAlchemy 1.4, connecting procedure fails with an error:
`sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'None'`

More details:
https://github.com/googleapis/python-spanner-sqlalchemy/pull/26/files

To make the package work with SQLAlchemy 1.4, we need to change connection URL - actually to add the `spanner.` prefix into it, and the same prefix into the package registration. Thus, preliminary it looks like we can support either <= 1.3 or >=1.4 version, but not both. Taking a closer look...

**Comment by IlyaFaer** [comment]
I've tested the `entry_points` change to `spanner.spanner` with SQLAlchemy 1.3.24 and 1.4.23. Looks like now in principle we can use `spanner.spanner` for both of them.

Still, 1.4 test suite is little bit different than 1.3, so we'll have to update our tests to make them work with 1.4. And they'll not work with 1.3 anymore, but this seems to be related only to the testing system itself -  I don't see any functionality errors. Meaning if the tests are passing fine on 1.4 - they'll also pass on 1.3 (but to run them on 1.3 some code changes are required)

**Comment by skuruppu** [comment]
@IlyaFaer thanks for looking into this. Could we clone the tests and run them as two separate targets?

@larkee do you have any thoughts on how we can make this work?

**Comment by IlyaFaer** [comment]
@skuruppu, @larkee, it's little bit challenging, but I think I have some thoughts. The tests for 1.3 and 1.4 are not completely different - most of them will be the same for both versions. Considering that fact, I think we can do this:

- Split `test-suite.py` file to three different files: 1.3 tests, 1.4 tests and common tests.
- 1.3 and 1.4 tests will be executed by different `nox` sessions, while common tests will be just imported by 1.3 and 1.4 test suites to become a part of those suites.

Thus, we'll have only one instance of all the common tests and two versions for those tests, which can't work fine in both 1.3 and 1.4 - the duplication will be minimal.

**Comment by skuruppu** [comment]
@IlyaFaer that sounds like a plan. Thanks for looking into it.

**Comment by IlyaFaer** [comment]
Working on it. Hard to tell how much time it'll require, looks like in 1.4 more tests were added as there are more than 400 cases now, while in 1.3 we have ~300.

**Comment by IlyaFaer** [comment]
The [PR](https://github.com/googleapis/python-spanner-sqlalchemy/pull/191) which prepared a test suite for SQLAlchemy 1.4 is now merged. All the tests passed, so I guess SQLAlchemy 1.4 support is implemented.

Closing the issue, feel free to open in case something's acted up during migration to 1.4 version.
