### ISSUE TITLE
`ModuleNotFoundError` with old version of google-cloud-spanner (3.9.0)

### ISSUE THREAD

**Issue by aderk** [googleapis/python-spanner-sqlalchemy#168]
#### Environment details

  - Programming language: python
  - OS: linux
  - Language runtime version: 3.8.8
  - Package version: 1.0.0

#### Steps to reproduce

  1. Use google-cloud-spanner 3.9.0 (3.12.0 is latest)
  2. Do anything (e.g. SELECT) with python-spanner-alchemy
  3. returns `ModuleNotFoundError: No module named 'google.cloud.spanner_v1.data_types'`

#### Steps to resolve:
Update google-cloud-spanner (3.12.0 works, I'm not sure what the minimal version required is)

**Comment by skuruppu** [comment]
Thanks for the report @aderk. @IlyaFaer would you please be able to look into this today?

**Comment by IlyaFaer** [comment]
@skuruppu, yes, we talked about this error some time ago. We updated JSON data type code, and now SQLAlchemy requires a higher version of `python-spanner`. Pushing changes for requirements.
