### ISSUE TITLE
Can't specify nullable state for generated columns

### ISSUE THREAD

**Issue by skuruppu** [googleapis/python-spanner-sqlalchemy#169]
#### Environment details

  - Programming language: Python
  - OS: Linux
  - Language runtime version: Python3.9
  - Package version: sqlalchemy-spanner-1.0.0

#### Steps to reproduce

1. Run the following snippet:
```
from sqlalchemy import (
  Column,
  Computed,
  MetaData,
  String,
  Table,
)

metadata = MetaData(bind=engine)

singers = Table(
    "Singers",
    metadata,
    Column("SingerId", String(36), primary_key=True, nullable=False),
    Column("FirstName", String(200)),
    Column("LastName", String(200), nullable=False),
    Column("FullName", String(400), Computed("COALESCE(FirstName || ' ', '') || LastName"), nullable=False),
)

metadata.create_all(engine)
```
2. I get the following error:
```
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Error parsing Spanner DDL statement: CREATE TABLE `Singers` (\n\t`SingerId` STRING(36) NOT NULL, \n\t`FirstName` STRING(200), \n\t`LastName` STRING(200) NOT NULL, \n\t`FullName` STRING(400) AS (COALESCE(FirstName || \' \', \'\') || LastName) STORED NOT NULL\n) PRIMARY KEY (SingerId) : Syntax error on line 5, column 80: Expecting \')\' but found \'NOT\'
```
3. It seems that we can't specify the `nullable` condition for generated columns.

**Comment by IlyaFaer** [comment]
@skuruppu, hm-m. I suspect the syntax is not supported by Spanner. According to the docs, it's impossible to directly write into a generated column. So, everything is up to the expression - there we're setting if it can contain `NULL`s, and there is no need in a separate `nullable` parameter. Should we throw an exception with explanation in case `nullable` was used with a generated column?

**Comment by skuruppu** [comment]
When we were working on EntityFramework, we were able to set this property. See this [data model](https://github.com/googleapis/dotnet-spanner-entity-framework/blob/main/Google.Cloud.EntityFrameworkCore.Spanner.QuickStart/DataModel.sql) for example.

Just to be sure, I ran the above DDL using the Cloud Console and it worked.

**Comment by IlyaFaer** [comment]
@skuruppu, oh, I see. The `NOT NULL` part is inserted in front of the `computed` part. Okay, let me see how we can fix it.
