### ISSUE TITLE
Support autoincrementing integer IDs in some capacity

### ISSUE THREAD

**Issue by aderk** [googleapis/python-spanner-sqlalchemy#176]
**Is your feature request related to a problem? Please describe.**
Autoincrementing serogate integer surrogate IDs are common among databases over the decades, and strongly recommended against within Cloud Spanner (https://cloud.google.com/spanner/docs/whitepapers/optimizing-schema-design [1]). I realize this is *not* an optimal solution, but it is a very compatible solution when schema migration is difficult for workloads with low latency / throughput requirements (this is python afterall).

Cloud spanner recommends a lot of application side boilerplate for generating autoincrementing IDs: https://cloud.google.com/solutions/sequence-generation-in-cloud-spanner#sequence_generators_using_database_table_rows [2]. TL;DR: Select the highest ID, increment, and insert all within a transaction is the simplest, most robust, and slowest option. I predict a lot of users migrating workloads to spanner will run into this issue and have to write their own code.

**Describe the solution you'd like**
sqlalchemy supports `sa.Column('col1', sa.Integer, autoincrement=True)`, but this is ignored by python-spanner-sqlalchemy (and an Error is raised during insertion that 'col1' was not supplied). Another option is `sa.Column('col1', sa.Integer, sa.Sequence('col1_auto_inc'))`, but table creation fails for lack of available sequences

Note: Both these tests were performed on the spanner emulator, not the actual thing. These might be emulator errors?

I'd like python-spanner-sqlalchemy to support either of the above solutions, or something similar.

**Describe alternatives you've considered**
The workaround is using a transaction, selecting the highest id, incrementing, and inserting within the same transaction (as listed in [2]). This requires reinventing the wheel for every insert for every user and application. It's not horrible, but it seems like adding it to the library would be ergonomic

**Comment by IlyaFaer** [comment]
@skuruppu, I suppose this request is mostly for the backend.

**Comment by skuruppu** [comment]
@aderk I may not have understood the request properly so I wanted to clarify. Do you actually want the IDs to increment in the table, or do you want the dialect to support `autoincrement=True` but you'd be ok with us generating a randomized ID when storing the value?

The reason I ask is that, Spanner doesn't support autoincrement to prevent [hotspotting issues](https://cloud.google.com/spanner/docs/schema-design#primary-key-prevent-hotspots). So if we do support autoincrement in an ORM, then we typically randomize the keys internally when we do the inserts. This may not give you the behavior you were expecting though.

**Comment by aderk** [comment]
> Do you actually want the IDs to increment in the table [...]

Yes. I understand this is discouraged for performance reasons. Also a response like "we don't have high priority (or a willingingness) to support features which are used for discouraged practices, so we won't implement this". However, when migrating legacy tables from schemae with auto-inc IDs to Cloud Spanner from postgres/etc., I think implementing auto-inc IDs application-side makes sense (hence the Spanner docs explaining how to mimic auto-inc application side.)

In practice, implementing it is actually rather easy, a la:
```python
with connection.begin():
    # Begin Spanner auto-inc application-side code
    top_id_res = connection.execute(
        sa.select([tbl.c.id]).order_by(tbl.c.id.desc()).limit(1)
    ).fetchall()
    next_id = top_id_res[0][0] + 1 if top_id_res else 1
    # End Spanner code
    ins = tbl.insert(None).values(
        id=next_id,  # This line can be omitted with other backends with autoincrement=true, but needs to be present for Could Spanner
        other_col=data,
    )
```

Perhaps just adding a snippet like this to the docs would (1) help with users migrating from auto-inc schema while (2) also discouraging its use and (3) making it explicit that auto-inc is client side rather than some python-spanner-sqlalchemy magic? I'll defer to your decision, but wanted to make you aware of my thoughts :) Thanks!

**Comment by skuruppu** [comment]
Thanks for the clarification @aderk.

In that case, I will say that we don't want to add explicit support for this in the dialect itself since we wouldn't want folks to use it unintentionally and cause perf issues. But I do like the idea of having a snippet in the docs (probably in the README) to say if you really need this, then here's how you can do it.

@IlyaFaer would you be ok with adding a section to the README about this? I'm happy to review it.
