### ISSUE TITLE
Does interleaving allow relationships?

### ISSUE THREAD

**Issue by gabrizappts** [googleapis/python-spanner-sqlalchemy#185]
- What you're trying to do
One of the big disadvantages using is the impossibility to use cascade deletion on foreign keys relations, so it's highly recommended to use interleaving. The docs provide some examples on how to achieve interleaved tables [here](https://github.com/googleapis/python-spanner-sqlalchemy#features-and-limitations), but when using it I was unable to build those relations in a class model or figure out how can I use a table as a secondary association table. So my question is: is there a way to do that using interleaved tables as secondary associations (like a many-to-many fashion)?
Something like:
```
products = relationship(
        "ProductModel", secondary=product_categories, backref="categories"
    )
```
- What code you've already tried
Snippet of an attempt of doing it with Association Object pattern:
```
from datetime import datetime
from sqlalchemy import Integer, Column, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql.sqltypes import Boolean, DateTime, String
from app.infrastructure.database.db import Base
from uuid import uuid4


class AllergenPresence(Base):
    __tablename__ = "allergen_presence"

    id = Column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid4()),
    )
    allergen_id = Column(
        Integer, ForeignKey("allergen.id", spanner_interleave_on_delete_cascade=True)
    )
    product_id = Column(
        String(36), ForeignKey("product.id", spanner_interleave_on_delete_cascade=True)
    )
    created_at = Column("created_at", DateTime, default=datetime.now)
    updated_at = Column(
        "last_updated", DateTime, default=datetime.now, onupdate=datetime.now
    )

    description = Column(String)
    may_have = Column(Boolean, default=False)
    contain = Column(Boolean, default=False)

    allergen = relationship("AllergenModel", back_populates="products")

    product = relationship("ProductModel", back_populates="allergens")
```

**Comment by IlyaFaer** [comment]
@gabrizappts, the first thing that should be mentioned, is that interleave relations are described for tables, not for specific columns and foreign keys ([see for more details](https://cloud.google.com/spanner/docs/schema-and-data-model#creating-interleaved-tables)). Next, without `spanner_interleave_in` arg set there is no interleaved relation, meaning setting the `spanner_interleave_on_delete_cascade` without `spanner_interleave_in` will take no effect.

As far as I understand your data model, the way you can achieve what you want is to create an association table and interleave your tables into it.

```python
Associations: parent_id
    Products: parent_id, product_id    (interleave in Associations)
   Allergens: parent_id, allergen_id   (interleave in Associations)
```
So, primary keys of the `Products` and `Allergens` tables include the `parent_id` as the first column. And when creating the `Products` and `Allergens` tables, there should be said that each is `spanner_interleave_in="Associations"` (and `spanner_interleave_on_delete_cascade` if you want it).

This should give you high efficiency. And for now I don't think you really need the `relationship()` calls, interleaving should be enough to do the trick.

**Comment by IlyaFaer** [comment]
Solution for the issue seems to be described. Closing.
Feel free to re-open in case you still have questions.
