### ISSUE TITLE
bug: compliance_test is failing

### ISSUE THREAD

**Issue by vi3k6i5** [googleapis/python-spanner-sqlalchemy#195]
#### Environment details

  - Programming language: python-8
  - OS: Mac
  - Language runtime version: python-8
  - Package version: latest

#### Steps to reproduce

  1. nox -s compliance_test

`___ ERROR at setup of RowFetchTest_spanner+spanner.test_row_w_scalar_select ____
Traceback (most recent call last):
  File "/home/runner/work/python-spanner-sqlalchemy/python-spanner-sqlalchemy/.nox/compliance_test/lib/python3.8/site-packages/pytest_asyncio/plugin.py", line 317, in pytest_fixture_setup
    warnings.warn(
DeprecationWarning: '@pytest.fixture' is applied to <fixture Class._inject_setup_class_fixture.<locals>.xunit_setup_class_fixture, file=/home/runner/work/python-spanner-sqlalchemy/python-spanner-sqlalchemy/.nox/compliance_test/lib/python3.8/site-packages/_pytest/python.py, line=802> in 'legacy' mode, please replace it with '@pytest_asyncio.fixture' as a preparation for switching to 'strict' mode (or use 'auto' mode to seamlessly handle all these fixtures as asyncio-driven).
_____ ERROR at setup of SimpleUpdateDeleteTest_spanner+spanner.test_delete _____`

**Comment by IlyaFaer** [comment]
Going to be fixed by the PR: https://github.com/googleapis/python-spanner-sqlalchemy/pull/191
