### ISSUE TITLE
Support SQLAlchemy 1.4+

### ISSUE THREAD

**Issue by potiuk** [googleapis/python-spanner-sqlalchemy#204]
Thanks for stopping by to let us know something could be better!

**Is your feature request related to a problem? Please describe.**
SQLAlchemy 1.4 has been released quite a while ago (November 2020) and it has mutliple improvments. Major applications has already moved to SQLAlchemy 1.4. For example Apache Airflow switched to 1.4+ a week ago: https://github.com/apache/airflow/pull/22114

This is also advised in https://www.sqlalchemy.org/download.html

> Please note: the 1.3 series is the current "Maintenance" series. Updates for critical fixes will be made available as needed, but applications which continue to be under active development are advised to begin upgrading to the current series of SQLAlchemy (currently the 1.4 series).

Lack of SQLAlchemy 1.4 support blokcs for example Apache Airflow Google Provider from adding spanner sqlalchemy support in Airflow Google Provider: https://github.com/apache/airflow/pull/21890#issuecomment-1069022955

**Describe the solution you'd like**
SQLalchemy 1.4 should be supported.

**Describe alternatives you've considered**
The alternative is to not add spanner sqlalchemy suport to Google Provider for Apache Airflow (which also prevents Composer from Google from supporting it).

**Additional context**
SQLallchemy spanner support is not strictly necessary for Google Provider but it would be great to add it.

**Comment by ansh0l** [comment]
@potiuk : I think this was covered in https://github.com/googleapis/python-spanner-sqlalchemy/issues/177 . However, @vi3k6i5 would know the best update.

**Comment by potiuk** [comment]
Yeah. It would be great to get it changed and released. I am happy to provide a PR for that if needed :)

**Comment by ansh0l** [comment]
We're currently working our way around some tests for this issue, so bumping up the priority. 

PR: https://github.com/googleapis/python-spanner-sqlalchemy/pull/207/files

**Comment by potiuk** [comment]
Looking forward to it !

**Comment by asthamohta** [comment]
SQLAlchemy 1.4 support is now available.

**Comment by potiuk** [comment]
woooho!!!
