### ISSUE TITLE
Adding unique constraint generates bad migration

### ISSUE THREAD

**Issue by louimet** [googleapis/python-spanner-sqlalchemy#228]
#### Environment details

OS: Windows 10
Programming language: Python
Language runtime version: 3.9.12
sqlalchemy-spanner version: 1.2.1
google-cloud-spanner version: 3.17.0
alembic version : 1.8.1

#### Steps to reproduce

Add a 'unique' constraint to a model thus:

```
class Tag(Base):
    __tablename__ = 'tag'
    tag = Column(String, primary_key=True)
    test = Column(String, unique=True)
```

#### Output

Whether this line is added to an existing model or when creating a new one, the line generated for the migration is either `op.create_unique_constraint(None, ['test'])` in an op.batch_alter_table(), or `sa.UniqueConstraint('version')` in an op.create_table().

Running either of those during a migrations gives the following error: 

`google.cloud.spanner_dbapi.exceptions.ProgrammingError: Spanner doesn't support direct UNIQUE constraints creation. Create UNIQUE indexes instead.`

**Comment by IlyaFaer** [comment]
Spanner doesn't support such a column attribute `unique`. To create a unique constraint an index should be declared, like in this example:
https://github.com/googleapis/python-spanner-sqlalchemy#unique-constraints

More info in Spanner docs:
https://cloud.google.com/spanner/docs/secondary-indexes#unique-indexes

**Comment by louimet** [comment]
Noted, thank you.

**Comment by MattOates** [comment]
Im not sure why this was closed. I'm using the same SQLModels for BigQuery, PostgreSQL and Spanner. Only Spanner chokes here, it should either just ignore the UNIQUE constraints and warn, not fully error out. Given Alembic doesn't understand this difference in dialect I'd say this is a bug against this repository.
