### ISSUE TITLE
Document how sqlalchemy handles transaction aborts or the best practice to handle transaction aborts (for the readwrite transactions)

### ISSUE THREAD

**Issue by yuanyuan-gl** [googleapis/python-spanner-sqlalchemy#246]
Could you please help document the best practice to handle transaction aborts and the errors like “The transaction was aborted and could not be retried due to a concurrent modification.”  There were multiple support cases asking about this. 

Thanks!

**Comment by asthamohta** [comment]
We are about to merge this: https://github.com/googleapis/python-spanner-sqlalchemy/pull/243
Thanks for reaching out!
