### ISSUE TITLE
Enable instance-level connection

### ISSUE THREAD

**Issue by yu-iskw** [googleapis/python-spanner-sqlalchemy#312]
**Is your feature request related to a problem? Please describe.**
We can't connect an Spanner instance at the time of writing the issue under v1.3.0. We are allowed only to connect a Spanner database in an instance. 

**Describe the solution you'd like**
We would like to connect an instance so that we get a list of databases in a Spanner instance and so on with python-spanner-sqlalchemy.

```
spanner+spanner:///projects/project-id/instances/instance-id
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by asthamohta** [comment]
Hi @yu-iskw, sure we can support this but in this scenario you would need to create a new engine to connect to the database later. Does that work?

**Comment by yu-iskw** [comment]
That would work for our case!
