### ISSUE TITLE
Feature request - Adding support for INSERT OR UPDATE and INSERT OR IGNORE

### ISSUE THREAD

**Issue by mescanne** [googleapis/python-spanner-sqlalchemy#391]
Hello - it would be great to use sqlalchemy with Spanner with the INSERT OR UPDATE and INSERT OR IGNORE functionality.

This seems to be handled directly within the dialects, e.g., [here](https://github.com/zzzeek/sqlalchemy/blob/main/lib/sqlalchemy/dialects/postgresql/dml.py#L57). However, it's not clear how this should be handled with sqlalchemy for Spanner.

**Comment by andrew-petukhov** [comment]
Hello,
It is possible to use the following statement with no changes to library:
`insert(users).prefix_with("OR IGNORE").values(dict(id=1, name="name1"))`
which will render to
`'INSERT OR IGNORE INTO users (id, name) VALUES (:id, :name)'`

Please notice that this statement is not supported yet in spanner emulator.
